openapi: "3.0.0"
info:
  version: 1.0.0
  title: bot
  description: handles webhook messages and executes plugins based on message content
servers:
  - url: https://{hostname}
    variables:
      hostname:
        default: localhost
paths:          
  /pubsub/subscriptions/video-saved:
    post:
      operationId: handleVideoSavedMessage
      requestBody:
        description: handles messages from video saved topic
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPubSubMessage"
      responses:
        "200":
          description: video was sucessfully published to telegram
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /telegram/callback:
    post:
      operationId: handleTelegramMessage
      requestBody:
        description: handles messages from telegram webhook
        required: true
        content:
          application/json:
           schema:
            type: object
            nullable: true
      responses:
        "200":
          description: message was handled
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    PostPubSubMessage:
      type: object
      required: [id, data, publishTime]
      properties:
        id:
          type: string
          format: uuid
        data:
          type: string
          format: byte
        publishTime:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
