// Package port provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package port

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// PostPubSubMessage defines model for PostPubSubMessage.
type PostPubSubMessage struct {
	Data        []byte     `json:"data"`
	MessageId   *string    `json:"message_id,omitempty"`
	PublishTime *time.Time `json:"publish_time,omitempty"`
}

// HandleVideoUrlPublishedMessageJSONRequestBody defines body for HandleVideoUrlPublishedMessage for application/json ContentType.
type HandleVideoUrlPublishedMessageJSONRequestBody = PostPubSubMessage
