openapi: "3.0.0"
info:
  version: 1.0.0
  title: Telegrofler downloader
  description: Converts webms and urls to mp4 videos
servers:
  - url: https://{hostname}/api
    variables:
      hostname:
        default: localhost
paths:
  /saved-videos/{videoId}:
    get:
      operationId: getSavedVideo
      parameters:
        - in: path
          name: videoId
          description: The ID of the video
          schema:
            type: string
            format: uuid
          required: true
      responses:
        "200":
          description: OK
          content:
            video/mp4:
              schema:
                type: string
                format: binary
          headers:
            Content-Disposition:
              description: The filename of the video file
              schema:
                type: string
              example: attachment; filename="video.mp4"
        "404":
          description: Video not found or link is expired
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /pubsub/subscriptions/video-url-published:
    post:
      operationId: handleVideoUrlPublishedMessage
      requestBody:
        description: Handles messages from url published topic
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPubSubMessage"
      responses:
        "200":
          description: Video was sucessfully downloaded
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    PostPubSubMessage:
      type: object
      required: [id, data, publishTime]
      properties:
        id:
          type: string
          format: uuid
        data:
          type: string
          format: byte
        publishTime:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
