openapi: "3.0.0"
info:
  version: 1.0.0
  title: downloader
  description: converts webms and urls to mp4 videos
servers:
  - url: https://{hostname}
    variables:
      hostname:
        default: localhost
paths:          
  /pubsub/subscriptions/video-url-published:
    post:
      operationId: handleVideoUrlPublishedMessage
      requestBody:
        description: handles messages from url published topic
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostPubSubMessage"
      responses:
        "200":
          description: video was sucessfully downloaded
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    PostPubSubMessage:
      type: object
      required: [id, data, publishTime]
      properties:
        id:
          type: string
          format: uuid
        data:
          type: string
          format: byte
        publishTime:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - slug
        - message
      properties:
        slug:
          type: string
        message:
          type: string
