// Package port provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package port

import (
	"time"

	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// PostPubSubMessage defines model for PostPubSubMessage.
type PostPubSubMessage struct {
	Data        []byte             `json:"data"`
	Id          openapi_types.UUID `json:"id"`
	PublishTime time.Time          `json:"publishTime"`
}

// HandleTelegramMessageJSONBody defines parameters for HandleTelegramMessage.
type HandleTelegramMessageJSONBody = map[string]interface{}

// HandleVideoSavedMessageJSONRequestBody defines body for HandleVideoSavedMessage for application/json ContentType.
type HandleVideoSavedMessageJSONRequestBody = PostPubSubMessage

// HandleTelegramMessageJSONRequestBody defines body for HandleTelegramMessage for application/json ContentType.
type HandleTelegramMessageJSONRequestBody = HandleTelegramMessageJSONBody
