#AK TODO currently not in use
name: Fetch secrets
description: Fetches secrets
inputs:
  image-name:
    description: Image name to deploy
    required: true
  credentials-json:
    description: Image name to deploy
    required: true

outputs:
  app-name:
    description: Prod application name
    value: ${{ steps.secrets-manager.outputs.app-name }}"

  telegram-bot-token:
    description: Telegram bot token
    value: ${{ steps.secrets-manager.outputs.telegram-bot-token }}

  project-id:
    description: Project id
    value: ${{ steps.auth.outputs.project_id }}

runs:
  using: composite

  steps:
  - uses: 'actions/checkout@v3'

  - id: auth
    name: Authenticate to Google Cloud
    uses: 'google-github-actions/auth@v0'
    with:
      credentials_json: ${{ secrets.GCP_CREDENTIALS }}

  - id: secrets-manager
    uses: google-github-actions/get-secretmanager-secrets@v0
    with:
      secrets: |-
        telegram-bot-token:${{ steps.auth.outputs.project_id }}/telegram_bot_token
        app-name:${{ steps.auth.outputs.project_id }}/app_name
