# AK TODO is kept there just because github docs on reusable actions are pain in the ass to find
name: Build and publish new container version 
description: Build and tests sources and pushes container to gcloud artifact registry
inputs:
  image-name: # AK TODO this is the first iteration
    description: Image name to deploy
    required: true
  credentials-json:
    description: Image name to deploy
    required: true

outputs:
   image-name:
    description: Pushed image
    value: ${{ steps.image-name-output.outputs.random-number }}

runs:
  using: composite
  steps:
  - name: Checkout repository
    uses: actions/checkout@v2

  - name: Set up Cloud SDK
    uses: google-github-actions/setup-gcloud@v0
    with:
      service_account_key: ${{ inputs.credentials-json }}

  - name: Configure Docker
    shell: bash
    run: gcloud auth configure-docker --quiet

  - name: Build Docker image
    shell: bash
    run: docker build . -t ${{ inputs.image-name }} # AK TODO should actually use env variable???

  # - Extract tests to a new job
  # - name: Test Docker image
  #   shell: bash
  #   run: docker run ${{ inputs.image-name }} sh -c "go test -v"

  - name: Push Docker image
    shell: bash
    run: docker push ${{ inputs.image-name }}