name: Bot delete PR

on:
  pull_request:
    types: [closed]

jobs:
  delete-cloud-run:
    runs-on: ubuntu-latest
    environment: prod
    name: Deletes pr cloud run service

    steps:
      - uses: "actions/checkout@v3"

      - id: auth
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Delete service
        run: gcloud run services delete bot-${{github.event.number}} --region europe-central2 --quiet
