name: Bot deploy pr

on:
  pull_request:
    types: [opened, edited, synchronize]
    paths:
      - service/bot/**

jobs:
  golang-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '1.19'
          
      - uses: actions/checkout@v3
      - name: downloader golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.29
          working-directory: service/bot/**

  deploy-to-cloudrun:
    name: Deploys new version of telegrofler bot to a PR copy
    uses: ./.github/workflows/bot-reusable-deploy-cloudrun.yml
    with:
      service-postfix: ${{ github.event.number }}
      set-webhook: true
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
