name: Deploy Bot from PR

on:
  pull_request:
    types: [opened, edited, synchronize]
    paths:
      - "bot/**"

jobs:
  deploy-to-cloudrun:
    name: Deploys new version of telegrofler bot to a PR copy
    uses: ./.github/workflows/bot-reusable-deploy-cloudrun.yml
    with:
      service-postfix: ${{ github.event.number }}
      set-webhook: true
    secrets:
      GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
