name: Global Apply terraform

on:
  push:
    branches: [main]
    paths:
      - iac/gcp/**

  workflow_dispatch:
    inputs:
      env:
        description: Environment
        default: prod
        required: true
jobs:
  deploy-infra:
    name: Terraform
    environment: prod
    runs-on: ubuntu-latest

    env:
      TF_CLI_ARGS: ""
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }} # Terraform relies on this predefined env

    defaults:
      run:
        working-directory: ./iac/gcp

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          create_credentials_file: true

      - name: Populate TF cli args
        run: |
          echo "TF_VAR_project_id=${{ steps.auth.outputs.project_id }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform format
        run: terraform fmt -check

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
