name: Set callback for test bot. Runs only on PRs

on:
  workflow_dispatch:

jobs:
    delete-cloud-run:
      runs-on: ubuntu-latest
      environment: prod
      name: Deletes cloud run service

      steps:
      - uses: 'actions/checkout@v3'
      
      - id: pr
        name: Get Pull Request Number
        run: |
          echo "number=pull_request_number::$(gh pr view --json number -q .number || echo "")" >> $GITHUB_OUTPUT

      - name : Show PR Number
        run: echo Setting callback for PR ${{ ${{ steps.pr.outputs.number }} }}

      - id: auth
        name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - id: secrets-manager
        uses: google-github-actions/get-secretmanager-secrets@v0
        with:
          secrets: |-
            telegram-test-bot-token:${{ steps.auth.outputs.project_id }}/telegram_test_bot_token
            app-name:${{ steps.auth.outputs.project_id }}/app_name

      - id: describe
        name: Get service url
        env:
          CLOUD_RUN_SERVICE_NAME: ${{ steps.secrets-manager.outputs.app-name }}-${{ steps.pr.outputs.number }}
        run: |
          metadataJson=$(gcloud run services describe ${{ env.CLOUD_RUN_SERVICE_NAME }} --region=europe-central2 --format=json)
          echo "url=${{ fromJson(metadataJson).status.address.url }}"  >> $GITHUB_OUTPUT

      - uses: ./.github/actions/set-bot-callback
        with:
          bot-token: ${{ steps.secrets-manager.outputs.telegram-test-bot-token }}
          callback-url: ${{ secrets.describe.outputs.url }}